[versions]
agp = "8.13.2"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
annotation = "1.9.1"

xposed-api = "82"
xposed-api-sources = "82:sources"
yukiHookApi = "1.3.1"
yukiKspXposed = "1.3.1"
kavaref = "1.0.2"
kavaref-extension = "1.0.2"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api" }
xposed-api-sources = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api-sources" }
yukihook-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukiHookApi" }
yukihook-ksp-xposed = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukiKspXposed" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaref-extension" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }