name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GRADLE_USER_HOME: ${{ github.workspace }}\.gradle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Version Match
        shell: bash
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}

          GRADLE_VERSION=$(grep 'versionName' app/build.gradle.kts | sed -E 's/.*versionName = "(.*)".*/\1/')
          
          echo "Git Tag Version: $TAG_VERSION"
          echo "Gradle Version: $GRADLE_VERSION"

          if [ "$TAG_VERSION" != "$GRADLE_VERSION" ]; then
            echo "Error: Version mismatch!"
            echo "Tag is '$TAG_VERSION' but build.gradle.kts says '$GRADLE_VERSION'"
            exit 1
          fi
          echo "Version match confirmed."

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        shell: bash
        run: |
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > app/release-keystore.jks

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.GRADLE_USER_HOME }}\caches
            ${{ env.GRADLE_USER_HOME }}\wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        env:
          SIGNING_KEY_STORE_PATH: release-keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: .\gradlew.bat assembleRelease

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/DeZUXposed-${{ github.ref_name }}.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/DeZUXposed-${{ github.ref_name }}.apk
          generate_release_notes: true